myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',
         views.cart_add,
         name='cart_add'),
    path('remove/<int:product_id>/',
         views.cart_remove,
         name='cart_remove'),
]

myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts import views as account_views
from shop import views as shop_views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('payment/', include('payment.urls', namespace='payment')),
     path('register/', account_views.register, name='register'),
        path('profile/', account_views.profile, name='profile'),
        path('login/', auth_views.LoginView.as_view(template_name='registration/login.html'), name='login'),
        path('logout/', auth_views.LogoutView.as_view(template_name='registration/logout.html'), name='logout'),
        path('password-reset/done/', auth_views. PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'), name='password_reset_done'),
        path('password-reset/', auth_views. PasswordResetView.as_view(template_name='registration/password_reset.html'), name='password_reset'),
        path('password-reset-confirm/<uidb64>/<token>/', auth_views. PasswordResetConfirmView.as_view(template_name='registration/password_confirm.html'), name='password_reset_confirm'),
        path('about/', shop_views.about,name='about'),
        path('returns/', shop_views.returns, name='returns'),
        path('contact/', shop_views.contact, name='contact'),
        path('privacy-policy/', shop_views.privacy_policy, name='privacy_policy'),
        path('payment-options/', shop_views.payment_options, name='payment_options'),
        path('cookie/', shop_views.cookie, name='cookie'),
        path('password-reset-complete/', auth_views. PasswordResetCompleteView.as_view(template_name='registration/password_complete.html'), name='password_reset_complete'),
    path('', include('shop.urls', namespace='shop')),
    path(
            'admin/password_reset/',
            auth_views.PasswordResetView.as_view(),
            name='admin_password_reset',
        ),
        path(
            'admin/password_reset/done/',
            auth_views.PasswordResetDoneView.as_view(),
            name='password_reset_done',
        ),
        path(
            'reset/<uidb64>/<token>/',
            auth_views.PasswordResetConfirmView.as_view(),
            name='password_reset_confirm',
        ),
        path(
            'reset/done/',
            auth_views.PasswordResetCompleteView.as_view(),
            name='password_reset_complete',
        ),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.urls import path
from . import views


app_name = 'shop'


urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, 
         name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail,
         name='product_detail'),
    path('about', views.about, name="about"),
    path('returns', views.returns, name='returns'),
    path('contact', views.contact, name='contact'),
    path('privacy-policy/', views.privacy_policy, name='privacy_policy'),
    path('cookie/', views.cookie, name='cookie'),
    path('payment-options/', views.payment_options, name='payment_options'),
]

myshop/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('shop:product_list_by_category',
                           args=[self.slug])



class Product(models.Model):
    id = models.AutoField(primary_key=True)
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
            return reverse('shop:product_detail',
                           args=[self.id, self.slug])

myshop/shop/views.py
from django.shortcuts import render , get_object_or_404
from django.urls import reverse
from .models import Category, Product

from cart.forms import CartAddProductForm
# Create your views here.


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request,
                  'shop/product/detail.html',
                  {'product': product,'cart_product_form': cart_product_form})
def about(request):
    return render(request, 'shop/about.html', {})

def returns(request):
  return render(request, 'shop/returns.html', {})

def contact(request):
  return render(request,'shop/contact.html', {})

def cookie(request):
  return render(request,'shop/cookie.html', {})  


def privacy_policy(request):
  return render(request,'shop/privacy_policy.html', {})

def payment_options(request):
  return render(request,'shop/payment_options.html', {}) 

myshop/shop/templates/shop/about.html
{% extends "shop/base.html" %}
{% block content %}
</br>
</br>
</br>
</br>
 <div class="content-section">
 	<fieldset class="form-group">
 		<legend class="border-bottom mb-4">  <i class="fas fa-info-circle"></i>  About Us</legend></fieldset>
 		<font face="arial" size="+1">
  		  Mouhamed Sock, Co-fondateur et Président, a l’idée du projet fin 2020 et la première version du service Eshop, dévéloppé lui meme est lancée dans le net en  2021. Très vite, le service rencontre son public, au Senegal notamment grâce au travail de ce dernier. Wilfried, Co-fondateur et CEO, organise rapidement la croissance et la structuration de L'eshop-ecommerce. Depuis, l’équipe s’est agrandie, le hub s’est installé à Dakar avec notre équipe de développeurs, commerciaux, marketing et communication.En Septembre 2022, l’équipe se renforce avec l’arrivée de Ousseynou Sagna comme Directeur Marketing, Martin comme Directeur des Opérations, et des experts en back-end. Waly Diouf, notre CTO nous rejoint fin 2022.
Nous avons également ouvert un bureau au Senegal autour de Ngor, et nous comptons etendre notre societe partout en Afrique au Togo ,en Côte d’Ivoire, et à Douala.C’est cette équipe dynamique et multi-culturelle qui fait la réussite et la fierté de CoinAfrique depuis le début. Avec une dizaine de nationalités représentées, Eshop se veut à l’image d’une Afrique métissée et talentueuse, tournée vers l’avenir.</font>
</div>
   
{% endblock content %}

myshop/shop/templates/shop/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>Eshop</title>
  <!-- Favicon -->
  <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
  <link href="{% static "css/foot.css" %}" rel="stylesheet">
  <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
   <link href="{% static "css/zearch.css" %}" rel="stylesheet">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css" %}">
  <!-- Bootstrap core CSS -->
  <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static "css/mdb.min.css" %}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static "css/style.min.css" %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>

<body>
    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

  <!-- Navbar -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url "shop:product_list" %}" target="_self">
        <img src="{% static "img/Logo1.png" %}">
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect"  href="{% url "shop:product_list" %}" target="_self"><i class="fas fa-home"></i> Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
        
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          <li class="nav-item">
            <a href="{% url "cart:cart_detail" %}" class="nav-link waves-effect">
              <span class="badge red z-depth-1 mr-1">{% with total_items=cart|length %}
    {% if cart|length > 0 %}
      {{ total_items }}
      
    
    {% else %}  {% endif %}
  {% endwith %}</span>
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
           <div class="navbar-nav">
            {% if user.is_authenticated %}
               <a class="nav-item nav-link" href="{% url 'profile' %}"><i class="fas fa-user-circle"></i> {{user.username}}</a--->
               <a class="nav-item nav-link" href="{% url 'logout' %}"><i class="fas fa-sign-out-alt"></i>  Logout</a>

            {% else%}
              <a class="nav-item nav-link" href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i>  Login</a>
              <a class="nav-item nav-link" href="{% url 'register' %}"><i class="far fa-user"></i>  Register</a>
            {% endif %}
            </div>
          
        </ul>

      </div>

    </div>
  </nav>
  <!-- Navbar -->

<div id="content">
    {% block content %}
    {% endblock %}
  </div>

  <footer class="footer">
     <div class="footer-content">
            <a href="{% url "shop:product_list" %}" ><img src="{% static "img/logo2.png" %}" alt="#"></a></div>
     <div class="container">
      <div class="row">
        <div class="footer-col">
          <h4>company</h4>
          <ul>
            <li><a href="{% url 'about' %}">About Us</a></li>
            <li><a href="{% url 'contact' %}">Contact Us</a></li>
            <li><a href="{% url 'privacy_policy' %}">privacy policy</a></li>
            
          </ul>
        </div>
        <div class="footer-col">
          <h4>get help</h4>
          <ul>
            <li><a href="{% url 'cookie' %}">Cookie</a></li>
            <li><a href="{% url 'returns' %}">returns</a></li>
            
            <li><a href="{% url 'payment_options' %}">payment options</a></li>
          </ul>
        </div>
       
        <div class="footer-col">
          <h4>follow us</h4>
          <div class="social-links">
            <a href="https://www.facebook.com/Mouhamed.sock03/"><i class="fab fa-facebook-f"></i></a>
            <a href="https://twitter.com/Mouhamedsock0"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="https://www.linkedin.com/in/pape-mouhamadou-m-sock-bb7a68170/"><i class="fab fa-linkedin-in"></i></a>
          </div>
        </div>
         <!--Copyright-->
      <div class="footer-bottom">
            <p>Copyright &copy;2021 Eshop. Designed By <span>PMMS</span></p>
        </div>
    <!--/.Copyright-->
      </div>
     </div>
     
  </footer>

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static "js/jquery-3.4.1.min.js" %}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static "js/popper.min.js" %}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static "js/mdb.min.js" %}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>

</html>

myshop/shop/templates/shop/contact.html
{% extends "shop/base.html" %}
{% block content %}
</br>
</br>
</br>
</br>
 <div class="content-section">
 	<fieldset class="form-group">
 		<legend class="border-bottom mb-4">    <i class="fas fa-headphones"></i>  Contact Us</legend></fieldset>
 		<font face="arial" size="+1">
  		 Un Probleme? contacter nous sur notre numero telephone via whatsapp ou bien appeler sur ce numero: +221781167742</font>
</div>
   
{% endblock content %}

myshop/shop/templates/shop/cookie.html
{% extends "shop/base.html" %}
{% block content %}
</br>
</br>
</br>
</br>
 <div class="content-section">
 	<fieldset class="form-group">
 		<legend class="border-bottom mb-4">    <i class="fas fa-headphones"></i>  Cookies</legend></fieldset>
 		<font face="arial" size="+1">
  		 Un Probleme? contacter nous sur notre numero telephone via whatsapp ou bien appeler sur ce numero: +221781167742</font>
</div>
   
{% endblock content %}

myshop/shop/templates/shop/payment_options.html
{% extends "shop/base.html" %}
{% block content %}
</br>
</br>
</br>
</br>
 <div class="content-section">
 	<fieldset class="form-group">
 		<legend class="border-bottom mb-4">    <i class="fas fa-headphones"></i>  Payments Options</legend></fieldset>
 		<font face="arial" size="+1">
  		 Nous proposons un moyen de payment qui est le Stripe</font>
</div>
   
{% endblock content %}

myshop/shop/templates/shop/privacy_policy.html
{% extends "shop/base.html" %}
{% block content %}
</br>
</br>
</br>
</br>
 <div class="content-section">
 	<fieldset class="form-group">
 		<legend class="border-bottom mb-4">    <i class="fas fa-headphones"></i>  Privacy Policy</legend></fieldset>
 		<font face="arial" size="+1">
  		 Un Probleme? contacter nous sur notre numero telephone via whatsapp ou bien appeler sur ce numero: +221781167742</font>
</div>
   
{% endblock content %}

myshop/shop/templates/shop/returns.html

{% extends "shop/base.html" %}
{% block content %}
</br>
</br>
</br>
</br>
 <div class="content-section">
 	<fieldset class="form-group">
 		<legend class="border-bottom mb-4">About Us</legend></fieldset>
 		<font face="arial" size="+1">
  		 Amazon.fr et un grand nombre de vendeurs sur Amazon.fr vous proposent de retourner la plupart des articles dans un délai de 30 jours suivant leur réception. Cette page vous en apprend davantage sur nos politiques de retour. La plupart des articles vendus sur Amazon.fr bénéficient de notre politique de retour générale, mais certains produits sont soumis à des politiques de retours particulières.
  		Veuillez noter que chaque article doit être retourné dans le même état qu'au moment de leur réception. Les articles en état neuf doivent être retournés neufs, inutilisés et complets. Les articles d'occasion ne doivent pas comporter de signes d'utilisation ou de dommages supplémentaires. Les exceptions applicables au droit de rétractation s’appliquent aussi à notre Politique de Retours sous 30 jours. Les produits ci-dessous ne peuvent être retournés dans le cadre de notre Politique de Retours sous 30 jours (sauf si le produit est défectueux).

Les produits qui ne peuvent pas être retournés pour des raisons d'hygiène ou de protection de la santé et qui descellés ou bien, qui ont, après avoir été livrés, été mélangés de manière indissociables avec d'autres articles ;
Les enregistrements audio ou vidéo ou de logiciels informatiques lorsque vous les avez descellés après la livraison ;
Les produits qui ont été confectionnés selon vos spécifications ou nettement personnalisés, en particulier les articles personnalisés Amazon Handmade.
Les produits susceptibles de se détériorer ou de se périmer rapidement ;
Les services pleinement exécutés par Amazon pour lesquels vous avez accepté, au moment du passage de votre commande que nous commencions leur exécution, et renoncé à votre droit de rétractation ;
Le contenu numérique (y compris des applications, des logiciels, des livres numériques, téléchargement de musique, etc.) non fourni sur un support matériel (ex : sur un CD ou DVD) pour lequel vous avez accepté, au moment du passage de votre commande que nous commencions la fourniture de celui-ci et renoncé à votre droit de rétractation ;
Les journaux, périodiques ou magazines à l'exception des contrats d'abonnement à ces publications ;
Les boissons alcoolisées dont la valeur convenue à la conclusion du contrat dépend des fluctuations du marché échappant à notre contrôle.
Remarque: veuillez noter que, comme indiqué dans notre politique de retour, un article retourné doit être dans le même état dans lequel vous l'avez reçu. Cela signifie que les nouveaux articles doivent être retournés dans l'état exact dans lequel vous les avez reçus (y compris avec tous les accessoires).

Garantie légale de conformité
Ces politiques de retour n'affectent pas la garantie légale de conformité et/ou la garantie des vices cachés dont vous pouvez bénéficier, le cas échéant. Consultez notre page d'aide sur ces garanties légales.

Politique de retours des vendeurs
La politique de retours proposée par les vendeurs Marketplace doit être au moins équivalente à celle proposée par Amazon.

Si vous retournez un article à un vendeur sans utiliser de suivi de colis, et que celui-ci n'arrive pas à destination, ou si vous refusez le colis à sa livraison comme méthode de retour, il se peut que vous ne soyez pas éligible à une réclamation au titre de la Garantie A à Z.

Livres
Les livres achetés auprès d'Amazon.fr peuvent être retournés sous 30 jours. Vous serez guidé à chaque étape dans notre Centre de retours en ligne.

CD, vinyle, DVD, Blu-ray ou Jeux vidéo
Les CD, vinyle, DVD, Blu-ray et jeux vidéo expédiés par Amazon.fr doivent être retournés sous 30 jours, dans leur emballage d'origine, non descellés et incluant le code-barres. Toutefois, les CD, vinyle, DVD, Blu-ray et jeux vidéo envoyés par Amazon non scellés peuvent faire l'objet d'un retour dans leur condition d'origine, via notre Centre de retours en ligne.

Veuillez noter que les coffrets doivent nous être retournés en intégralité, et non seulement le CD, vinyle, DVD, Blu-ray ou jeu vidéo défectueux, endommagé ou non conforme.

Logiciels ou CD-Rom
Les logiciels et les CD-Rom doivent nous être retournés sous 30 jours, dans leur emballage d'origine, non descellés et incluant le code-barres via notre Centre de retours en ligne.

Articles volumineux
Si vous avez bénéficié de notre livraison spéciale sur rendez-vous, et souhaitez nous retourner un article de grande taille, notre transporteur viendra chercher votre article à votre domicile. Tous les détails d'organisation de cette collecte vous seront fournis dans notre Centre de retours en ligne.

Dans les 30 jours suivant la réception de votre commande, Amazon vous propose la possibilité de remplacer votre produit ou de vous faire rembourser le prix du produit. Les frais de retour sont gratuits si l'article est défectueux, endommagé ou non conforme. Des frais de retour de 19,90 € seront déduits de votre remboursement si l'article est en bon état mais vous souhaitez simplement le retourner.

Si toutefois vous préfériez procéder vous-même au retour de votre produit, veuillez noter que les frais de retour d'un article volumineux peuvent être plus élevés que les frais de retour habituels. Vous pourrez ainsi devoir supporter des frais de retour estimés jusqu'à 50 € pour un article volumineux.

Les retours peuvent être effectués à partir de notre Centre de retours en ligne.

Notre transporteur viendra chercher votre article à votre domicile.

Après la fenêtre de retours de 30 jours, si vous avez besoin d'une réparation, nous vous invitons à contacter en premier lieu le service après-vente du fabricant de la marque de votre produit.

Plusieurs marques de gros électroménager ne couvrent que les pièces dans leur garantie. Cela signifie qu'en cas de réparation, la main-d'œuvre et le déplacement peuvent être à votre charge. Puisque cette politique diffère des pratiques des marques sur d'autres types de produits électroniques, Amazon voudrait attirer votre attention sur ce point.

Chaussures et vêtements
Si vous souhaitez nous retourner une paire de chaussures ou un vêtement livrés en France métropolitaine, vous pouvez bénéficier d'un retour gratuit quelle que soit la raison du retour. Pour en savoir plus sur le retour de ces articles, ou lire nos conseils pour l'essayage de vos chaussures, rendez-vous sur la page Retours gratuits sur les articles de mode.

Le retour des articles des Collections The Drop créés sur demande lorsque l'article n'est pas défectueux, endommagé ou incorrect ne sont pas éligibles au retour gratuit.</font>
</div>
   
{% endblock content %}